Repository falcosecurity/falco-playground, pull requests merged in 2023-09, with the labels that each got.

#11 Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#12 Add a favicon for browser tabs
  index.html
  src/assets/falco-icon-color.svg
Labels: dco-signoff: yes, approved, area/frontend, kind/design, lgtm, size/XS

#15 Create a new workflow to run cypress tests when a new pull request is made
  .github/workflows/pr-tests.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#17 update: add additional checks when loading wasm file
  .github/workflows/deploy.yaml
  .github/workflows/pr-tests.yaml
  src/components/Content/Content.tsx
Labels: kind/bug, dco-signoff: yes, size/M, approved, area/frontend, lgtm

#21 Add test for "Import Yaml" + Add fixtures
  cypress/e2e/home.cy.ts
  cypress/fixtures/rule.yaml
  package-lock.json
  package.json
Labels: kind/feature, dco-signoff: yes, size/M, approved, area/tests, lgtm
