Repository falcosecurity/falco-playground, pull requests merged in 2023-10, with the labels that each got.

#23 Update cli test command in README.md
  readme.md
Labels: kind/bug, dco-signoff: yes, approved, area/tests, lgtm, size/XS

#25 Add ws as a new dependency and update cypress version
  cypress/e2e/home.cy.ts
  package-lock.json
  package.json
Labels: dco-signoff: yes, approved, lgtm, size/L

#26 cleanup(worker): prevent spawning of multiple yaml workers
  src/components/Editor/Monaco.tsx
  src/components/Editor/yaml.worker.js
  vite.config.ts
Labels: dco-signoff: yes, approved, area/frontend, kind/cleanup, lgtm, size/S

#31 fix: On-hover text color to white in mobile view
  src/components/Navbar/navbar.css
Labels: kind/bug, dco-signoff: yes, approved, area/frontend, lgtm, size/XS

#41 WIP : Dark theme
  index.html
  package-lock.json
  package.json
  src/components/DarkMode/DarkMode.tsx
  src/components/Editor/monaco.style.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/navbar.css
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/sidebar.css
  src/components/Sidebar/sidebar.style.ts
  vite.config.ts
Labels: dco-signoff: yes, approved, lgtm, hacktoberfest, size/XL, do-not-merge/work-in-progress
